// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL6mJjKPMMU-QOnNwYkkk_TULY-ZWYti8',
    appId: '1:144027754020:web:588fc47aff76e2b24302b1',
    messagingSenderId: '144027754020',
    projectId: 'flutter-cookbook-b5226',
    authDomain: 'flutter-cookbook-b5226.firebaseapp.com',
    storageBucket: 'flutter-cookbook-b5226.firebasestorage.app',
    measurementId: 'G-EELM9QFGQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaJYDkGDZaMQgCNdabkZT1YiDyQ4xzasI',
    appId: '1:144027754020:android:bbf8ed6f047d9bcb4302b1',
    messagingSenderId: '144027754020',
    projectId: 'flutter-cookbook-b5226',
    storageBucket: 'flutter-cookbook-b5226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvBYe2YKYM2P3HIT-C76yDudO5kYzThyw',
    appId: '1:144027754020:ios:aac6e69d7030c2814302b1',
    messagingSenderId: '144027754020',
    projectId: 'flutter-cookbook-b5226',
    storageBucket: 'flutter-cookbook-b5226.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvBYe2YKYM2P3HIT-C76yDudO5kYzThyw',
    appId: '1:144027754020:ios:aac6e69d7030c2814302b1',
    messagingSenderId: '144027754020',
    projectId: 'flutter-cookbook-b5226',
    storageBucket: 'flutter-cookbook-b5226.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL6mJjKPMMU-QOnNwYkkk_TULY-ZWYti8',
    appId: '1:144027754020:web:5c5dddc28dd42b584302b1',
    messagingSenderId: '144027754020',
    projectId: 'flutter-cookbook-b5226',
    authDomain: 'flutter-cookbook-b5226.firebaseapp.com',
    storageBucket: 'flutter-cookbook-b5226.firebasestorage.app',
    measurementId: 'G-65277D1204',
  );
}
